pipeline {
    agent any
    
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        
        stage('Install Requirements') {
            steps {
                dir('01-jenkins-basics/') {
                    sh '''
                        python3 -m venv venv
                        . venv/bin/activate
                        pip install -r requirements.txt
                    '''
                }
            }
        }
        
        stage('Run Tests') {
            steps {
                dir('your-app-subdirectory') {
                    sh '''
                        . venv/bin/activate
                        pytest
                    '''
                }
            }
        }
    }
}
